### ISSUE TITLE
Migrate code and issues from toolisticon repo

### ISSUE THREAD

**Issue by zambrovski** [AxonFramework/extension-kotlin#4]
As we created a small foundation for the library, this should not be re-implemented but migrated to this codebase.

See https://github.com/toolisticon/axon-extension-kotlin/issues

**Comment by snowe2010** [comment]
Same as with my existing extensions. https://github.com/snowe2010/axon-kotlin

**Comment by snowe2010** [comment]
@zambrovski @jangalinski 

After reviewing the toolisticon/axon-extension-kotlin repo I would recommend not using any code from there. 

I noticed some suspiciously familiar code and upon reviewing it appears that `toolisticon` copied some of my extension code word-for-word. While this isn't a problem because *my code is open source and I don't really care who copies it*, it is a problem **because `toolisticon` failed to include the MIT license when doing so**. 

I'm unsure of what other code `toolisticon` could have copied and since I'm absolutely sure that my code is completely original I believe it will jeopardize the project less if someone comes in and claims copyright for some copied code. I would recommend not copying any code from there for now unless `toolisticon` can provide licenses for all the copied code. 

Once again, I don't really have a problem with copying code (as long as the license is followed), I just think that with a high-profile project like Axon Framework we need to be a bit more careful about making sure we have license to use the copied code. 

For my project I can relicense all the commits since I'm the sole contributor.

Sincerely,
	Tyler Thrailkill

P.S. I would also like toolisticon to add in the MIT license for the code they copied from me 😉

**Comment by zambrovski** [comment]
Dear Tyler,

the intention of toolisticon/extension-kotlin was to create a reposity that should be transfered to AxonIQ 1:1 (by transfer ownership) and include the maximum of the features in kotlin language. Since AxonIQ uses not MIT license, we adjusted the license to become "axon extension"....

This is what we at least discussed on Axoniq conference with Axoniq employees.

Things went differently and axoniq created a new repo - so my plan was not to copy your code, but get rid of everything I found so far - I just made a mistake not to look that you use MIT license.

I will immediately delete any code from you from toolisticon repository and will contribute only our own parts to the extension.

I'm very sorry for the license mistake.

Kind regards,

Simon

**Comment by snowe2010** [comment]
Simon,

No worries, I have been bugging AxonIQ about adding kotlin extensions for years now. I can easily update my license, but the worrisome part was the non-disclosure of my license. 

Tyler

**Comment by zambrovski** [comment]
Tyler,

as far as I know, if the extension is "maintained" / "supported" by AxonIQ, the license states "AxonIQ" to be the license issuer ( see here: https://github.com/toolisticon/axon-extension-kotlin/blob/8b7fd2f839616c52caee612fdac6edffafc041c3/LICENSE.txt#L190 )

So I wonder how to combine "your" license and AxonIQ license.... I think the idea of official extension is to run with license issued to AxonIQ

Cheers,

Simon

**Comment by snowe2010** [comment]
Sure, but if we were to copy my code, it's currently MIT so you would need to provide MIT as the license. If I switch it to Apache we only need to include my name (I think). We can work with AxonIQ's lawyers to figure out the details if it comes to that.

**Comment by zambrovski** [comment]
Tyler, 

Since you are completely right in your license claim, I just deleted the toolisticon/extension-kotlin repository to avoid any legal discussions. I want to focus on development of extension and not on legal stuff. 

P.S. Feel free to contribute your part directly here, if you are still willing to do so...

Cheers,

Simon

**Comment by snowe2010** [comment]
Oh wow, you definitely didn't need to do that. I was mentioning AxonIQ's lawyers to help move _my_ code to Apache, not in relation to your code. Now I'm unsure how to handle my part of this. We'll need to discuss with Stefan and see what he thinks. I still think we'll probably need to work with lawyers to help me transition my code to AxonIQ's codebase.

**Comment by zambrovski** [comment]
I think this is easy. It is your code, so you are the owner. So you can easily contribute your 11 test methods to this extension complying to the new license. I don't think there are any license issues then. There is https://cla-assistant.io/ for contribution. We can ask Steven to set it up for this repository...

It would be great to get your pull reqest on this. I can then add the parts I developed later.

**Comment by zambrovski** [comment]
I just realised that cla-assistant is not a public service for any license, is only one for code contributed to Camunda libraries. I hope there is something comparable on github.

**Comment by smcvb** [comment]
We'll get things resolved, I am sure of this. Me, @sandjelkovic and @abuijze will discuss how/what to do regarding the licensing part. And, we'll keep you guys posted of course :+1:
